# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-15 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181107_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emallver',
            old_name='emall',
            new_name='email',
        ),
    ]
